# Generated by Django 3.1.4 on 2021-01-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_id', models.IntegerField(default=-1)),
                ('owner_time_period_id', models.IntegerField(default=-1)),
                ('owner_id', models.IntegerField(default=-1)),
                ('helper_time_period_id', models.IntegerField(default=-1)),
                ('helper_id', models.IntegerField(default=-1)),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('dog_id', 'owner_time_period_id', 'owner_id', 'helper_time_period_id', 'helper_id', 'is_accepted'), name='match duplicate'),
        ),

        migrations.RenameField(
            model_name='match',
            old_name='is_accepted',
            new_name='is_match_accepted',
        ),
    ]
