# Generated by Django 3.1.3 on 2020-12-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_login', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
