# Generated by Django 3.1.4 on 2021-01-07 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dog_editing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register_and_login', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('time_type', models.CharField(choices=[('O', 'occupied'), ('F', 'free')], default='F', max_length=1)),
                ('time_name', models.CharField(default='', max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DogTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.BooleanField(default=False)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog_editing.dog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_and_login.profile')),
                ('time_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_management.timeperiod')),
            ],
        ),
        migrations.AddConstraint(
            model_name='timeperiod',
            constraint=models.UniqueConstraint(fields=('person', 'day', 'start_hour', 'end_hour'), name='block duplicate'),
        ),
        migrations.AlterUniqueTogether(
            name='dogtime',
            unique_together={('dog', 'time_period')},
        ),
    ]
