# Generated by Django 3.1.4 on 2020-12-14 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[('N', 'needy'), ('H', 'helper')], default='N', max_length=1)),
                ('location', models.CharField(default='', max_length=30)),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/')),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('helping_radius', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('max_dog_amount', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0)),
                ('max_dog_size', models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('B', 'big')], default='N', max_length=5)),
                ('quarantine_time', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14)], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('B', 'big')], default='S', max_length=1)),
                ('short_description', models.CharField(max_length=300)),
                ('image', models.ImageField(default='profile_pics/dog_default.jpg', upload_to='profile_pics/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('day', 'start_hour'), ('day', 'end_hour'), ('start_hour', 'end_hour')},
            },
        ),
    ]
