# Generated by Django 3.1.3 on 2020-12-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='max_dog_size',
            field=models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('B', 'big')], default='S', max_length=5),
        ),
    ]
