# Generated by Django 3.1.3 on 2020-12-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogtime',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='timeperiod',
            options={'managed': True},
        ),
    ]
