# Generated by Django 3.1.3 on 2020-12-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_login', '0002_auto_20201230_1359'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dogtime',
            unique_together={('dog', 'time_period')},
        ),
    ]
