# Generated by Django 3.1.3 on 2020-12-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_login', '0003_auto_20201230_1405'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dogtime',
            unique_together=set(),
        ),
    ]
