# Generated by Django 3.1.4 on 2020-12-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_login', '0002_auto_20201218_1440'),
        ('register_and_login', '0003_auto_20201220_2114'),
    ]

    operations = [
    ]
