# Generated by Django 3.1.3 on 2020-12-29 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_login', '0004_auto_20201229_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.BooleanField(default=False)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_and_login.dog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_and_login.profile')),
                ('time_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_and_login.timeperiod')),
            ],
            options={
                'unique_together': {('dog', 'time_period')},
            },
        ),
    ]
