# Generated by Django 3.1.4 on 2020-12-30 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_login', '0006_auto_20201229_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogtime',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_and_login.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='timeperiod',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='timeperiod',
            constraint=models.UniqueConstraint(fields=('person', 'day', 'start_hour', 'end_hour'), name='block duplicate'),
        ),
    ]
