# Generated by Django 3.1.4 on 2020-12-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_login', '0007_auto_20201230_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeperiod',
            name='time_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='time_type',
            field=models.CharField(choices=[('O', 'occupied'), ('F', 'free')], default='F', max_length=1),
        ),
    ]
