# Generated by Django 3.1.4 on 2020-12-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_login', '0009_dogtime_xd'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogtime',
            name='xd',
            field=models.BooleanField(default=False),
        ),
    ]
