# Generated by Django 3.1.4 on 2020-12-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_login', '0010_dogtime_xd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogtime',
            name='xd',
        ),
    ]
