# Generated by Django 3.1.3 on 2021-01-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_login', '0004_auto_20201230_1405'),
        ('register_and_login', '0011_remove_dogtime_xd'),
    ]

    operations = [
    ]
