# Generated by Django 3.1.4 on 2021-01-07 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_login', '0008_auto_20201230_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogtime',
            name='dog',
        ),
        migrations.RemoveField(
            model_name='dogtime',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='dogtime',
            name='time_period',
        ),
        migrations.RemoveField(
            model_name='timeperiod',
            name='person',
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
        migrations.DeleteModel(
            name='DogTime',
        ),
        migrations.DeleteModel(
            name='TimePeriod',
        ),
    ]
